name: "Test Check"
on: push
jobs:
  build:
    name: check build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: backend/chain-api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Run Tests
        run: npm run test
  prettier:
    name: check prettier
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: backend/chain-api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check Prettier
        run: npx prettier --check .
